[package]
name = "open-hack-rust-starter"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "1.9.1"
fast-float = "0.2.0"
memchr = "2.7.2"
memmap = "0.7.0"
rayon = "1.10.0"
rustc-hash = "1.1.0"
